version: "3"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: backend-node
    restart: unless-stopped
    env_file: .env
    environment:
      - HOST=$HOST
      - DATABASE_MONGODB=$DATABASE_MONGODB
    ports:
      - "8000:8000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - elastic

  kibana01:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
  cron:
    build: cron
    container_name: cronjobs
    volumnes:
      - /var/log/cronjobs:/var/log/cronjobs
      - ./cron/cronjobs01:/etc/crontabs/root
      - ./sripts:/home/challenge_by_coodesh/src/
    networks:
      - app-network
